import pandas as pd
from catboost import CatBoostClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

print("--- Step 1: Loading Training Data ---")
# Load the CSV. We explicitly tell Pandas that 'flow_id' is the index, not a feature!
df = pd.read_csv('catboost_training_data.csv', index_col='flow_id')

print(f"Loaded {df.shape[0]} network sessions.")
print(df['target_label'].value_counts())

print("\n--- Step 2: Splitting Data (Train/Test) ---")
# X contains your 42 scaled/encoded features
X = df.drop(columns=['target_label'])

# y contains the text labels generated by the Zero-Shot LLM Teacher
y = df['target_label']

# Split the data. 80% to train the model, 20% held back to test it.
# stratify=y ensures both sets get a proportional amount of the rare malware anomalies
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print("\n--- Step 3: Training the CatBoost 'Student' Model ---")
# Initialize CatBoost. 
# auto_class_weights='Balanced' prevents the model from ignoring rare attacks.
model = CatBoostClassifier(
    iterations=500, 
    learning_rate=0.1, 
    loss_function='MultiClass',
    auto_class_weights='Balanced', 
    random_seed=42
)

# Train the model. It will use X_test/y_test to validate itself after every 50 trees.
model.fit(
    X_train, y_train, 
    eval_set=(X_test, y_test), 
    verbose=50,
    early_stopping_rounds=50 # Stops early if it stops improving, saving time
)

print("\n--- Step 4: Thesis Evaluation Metrics ---")
# Predict on the 20% of data the model has NEVER seen before
y_pred = model.predict(X_test)

# Print a formal classification report (Accuracy, Precision, Recall, F1-Score)
print(classification_report(y_test, y_pred))

print("\n--- Step 5: Exporting the Model ---")
# Save this trained brain so you can use it for real-time inference tomorrow!
model.save_model('suricata_threat_model.cbm')
print("Model saved as 'suricata_threat_model.cbm'. Training Pipeline Complete!")