import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

print("1. Loading error analysis data...")
# Make sure this points to the final file generated by your exact_correlation.py
try:
    df = pd.read_csv('Full_Model_Error_Analysis.csv')
except FileNotFoundError:
    print("Error: Could not find 'Full_Model_Error_Analysis.csv'. Run exact_correlation.py first!")
    exit()

# Set a professional academic style for the charts
sns.set_theme(style="whitegrid", context="paper", font_scale=1.2)

# Split datasets for easier plotting
fn_df = df[df['Error_Type'] == 'False Negative (Missed Attack)']
fp_df = df[df['Error_Type'] == 'False Positive (False Alarm)']

print("2. Generating figures...")

# ==========================================
# FIGURE 1: MISSED ATTACK TAXONOMY
# ==========================================
plt.figure(figsize=(10, 6))
# 'Label' is the column from your Ground Truth CSV (e.g., 'DoS Hulk', 'DoS Slowloris')
sns.countplot(
    data=fn_df, 
    y='Label', 
    order=fn_df['Label'].value_counts().index, 
    palette='Reds_r'
)
plt.title('Breakdown of Missed Attacks (False Negatives)', fontsize=14, fontweight='bold')
plt.xlabel('Number of Flows Missed by Firewall', fontsize=12)
plt.ylabel('Specific Attack Type (Ground Truth)', fontsize=12)
plt.tight_layout()
plt.savefig('Thesis_Fig1_Missed_Attacks.png', dpi=300)
plt.close()

# ==========================================
# FIGURE 2: MODEL CONFIDENCE DISTRIBUTION
# ==========================================
plt.figure(figsize=(10, 6))
sns.histplot(
    data=df, 
    x='Malicious_Probability', 
    hue='Error_Type', 
    bins=50, 
    kde=True, 
    palette={'False Negative (Missed Attack)': '#d62728', 'False Positive (False Alarm)': '#ff7f0e'},
    alpha=0.6
)
# Draw the 50% threshold line where the model makes its decision
plt.axvline(0.5, color='black', linestyle='--', linewidth=2, label='Decision Boundary (0.5)')
plt.title('Probability Distribution of Model Errors', fontsize=14, fontweight='bold')
plt.xlabel('Model Output Probability (Confidence it is Malicious)', fontsize=12)
plt.ylabel('Density / Number of Flows', fontsize=12)
plt.xlim(0, 1)
plt.legend(title='Type of Error')
plt.tight_layout()
plt.savefig('Thesis_Fig2_Confidence_Distribution.png', dpi=300)
plt.close()

# ==========================================
# FIGURE 3: TOP NOISY IPs (FALSE POSITIVES)
# ==========================================
plt.figure(figsize=(10, 6))
# 'Source IP' comes from your Ground Truth CSV
if 'Source IP' in fp_df.columns:
    top_fp_ips = fp_df['Source IP'].value_counts().head(10)
    sns.barplot(
        x=top_fp_ips.values, 
        y=top_fp_ips.index, 
        palette='Blues_r'
    )
    plt.title('Top 10 Source IPs Triggering False Alarms (False Positives)', fontsize=14, fontweight='bold')
    plt.xlabel('Number of False Alarms', fontsize=12)
    plt.ylabel('Source IP Address', fontsize=12)
    plt.tight_layout()
    plt.savefig('Thesis_Fig3_False_Positives_IPs.png', dpi=300)
    plt.close()
else:
    print("Skipped Figure 3: 'Source IP' column not found.")

print("\n--- Success! ---")
print("Check your folder for 3 new high-resolution PNG images ready for your thesis.")